serverAddr = "your_server_addr"
serverPort = 7000
auth.method = "token"
auth.token = "123456789"

log.to = "/share/frpc.log"
# trace, debug, info, warn, error
log.level = "trace"
log.maxDays = 3

[ssh]
type = "tcp"
local_ip = "127.0.0.1"
local_port = 8123
remote_port = 8123
