serverAddr = "your_server_addr"
serverPort = 7000
auth.method = "token"
auth.token = "123456789"

log.to = "/share/frpc.log"
# trace, debug, info, warn, error
log.level = "trace"
log.maxDays = 3

[[proxies]]
name = "hass-addon"
type = "tcp"
localIP = "127.0.0.1"
localPort = 8123
remotePort = 8123
